// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: ['./src/**/*.{html,ts}'],
    theme: {
        extend: {
            colors: {
                'on-tertiary': '#ffffff',
                'error': '#ba1a1a',
                'outline-variant': '#c1c6d7',
                'secondary-fixed-dim': '#c8c6c5',
                'tertiary': '#af2b30',
                'error-container': '#ffdad6',
                'on-secondary': '#ffffff',
                'surface-dim': '#dbdad9',
                'inverse-on-surface': '#f2f0f0',
                'surface-container-low': '#f5f3f3',
                'on-background': '#1b1c1c',
                'surface': '#fbf9f8',
                'outline': '#727786',
                'inverse-surface': '#303031',
                'tertiary-fixed-dim': '#ffb3af',
                'on-surface-variant': '#414754',
                'tertiary-container': '#d14446',
                'primary-container': '#0070f3',
                'on-secondary-fixed-variant': '#474746',
                'tertiary-fixed': '#ffdad7',
                'primary': '#0058c3',
                'on-surface': '#1b1c1c',
                'secondary-fixed': '#e5e2e1',
                'on-primary-fixed-variant': '#004397',
                'on-secondary-container': '#636262',
                'surface-tint': '#0059c5',
                'secondary-container': '#e2dfde',
                'secondary': '#5f5e5e',
                'on-secondary-fixed': '#1c1b1b',
                'background': '#fbf9f8',
                'surface-container-highest': '#e4e2e2',
                'on-tertiary-container': '#ffffff',
                'primary-fixed-dim': '#aec6ff',
                'on-tertiary-fixed-variant': '#8e101c',
                'on-primary-container': '#ffffff',
                'inverse-primary': '#aec6ff',
                'surface-container-high': '#e9e8e7',
                'primary-fixed': '#d8e2ff',
                'on-primary-fixed': '#001a43',
                'on-error': '#ffffff',
                'on-tertiary-fixed': '#410005',
                'surface-container': '#efeded',
                'surface-variant': '#e4e2e2',
                'surface-container-lowest': '#ffffff',
                'on-primary': '#ffffff',
                'surface-bright': '#fbf9f8',
                'on-error-container': '#93000a',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontFamily: {
                headline: ['Inter'],
                display: ['Inter'],
                body: ['Inter'],
                label: ['Inter'],
                mono: ['JetBrains Mono', 'monospace'],
            },
        },
    },
    plugins: [],
};