import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface FinancialTerm {
  label: string;
  value: string;
  sub: string;
}

export interface TermRow {
  label: string;
  value: string;
}

export interface TimelineStep {
  label: string;
  date: string;
  sub: string;
  completed: boolean;
}

export interface Document {
  icon: string;
  iconColor: string;
  name: string;
}

@Component({
  selector: 'app-offer-details',
  imports: [CommonModule],
  templateUrl: './offer-details.component.html',
  styleUrl: './offer-details.component.scss',
})
export class OfferDetailsComponent {

  // ── Sidebar nav ───────────────────────────────────────────
  readonly navLinks = [
    { icon: 'dashboard', label: 'Dashboard', active: false },
    { icon: 'group', label: 'Recruitment', active: true },
    { icon: 'payments', label: 'Payroll', active: false },
    { icon: 'settings', label: 'Settings', active: false },
  ];

  // ── Candidate ─────────────────────────────────────────────
  readonly candidate = {
    name: 'Sarah Jenkins',
    role: 'Senior Software Engineer',
    department: 'Engineering Department',
    id: 'CAND-8829',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD0AA5pV4vkRB_JumkqiXbhHWkIMdWuYJLFZcLo9eI8QAA_5MyB_csMMUx_wMNaidhPokVfeS6f0JDADu2yfAM3LVa_xJCtqzQU5-yjXuM030i1a_r9ir5t6H4VZAE7nM2rzwwPWpJpSCYaTL9V5X7JTraVey2dB-2kfiiSBId3uBm9Zgeqh0CH5ygO5vNaDFuGuqpxaorPb1JmJKTg1I-nxxpIIT8GHu9N7JxI_wHUcduuiVAA5tYcWP3ja9gD0hWz7bUEgJbUZjfk',
    status: 'Pending Response',
    type: 'Full-time',
    baseSalary: '$145,000.00',
    expiresIn: '3 days',
  };

  // ── Candidate details grid ────────────────────────────────
  readonly candidateDetails = [
    { label: 'Email Address', value: 'sarah.jenkins@email.com' },
    { label: 'Experience', value: '8 Years' },
    { label: 'Hiring Manager', value: 'David Miller' },
  ];

  readonly interviewScore = { score: '4.8 / 5.0', stars: 4, halfStar: true };

  readonly interviewerNote =
    '"Excellent technical problem solving skills. Showcased great architecture knowledge during the system design round. Culture fit is perfect for our team\'s pace."';

  // ── Financial terms ───────────────────────────────────────
  readonly financialTerms: FinancialTerm[] = [
    { label: 'Base Salary', value: '$145,000.00', sub: 'Per Annum' },
    { label: 'Equity (RSUs)', value: '2,500 units', sub: '4-year vesting' },
    { label: 'Sign-on Bonus', value: '$10,000.00', sub: 'One-time payment' },
  ];

  readonly termRows: TermRow[] = [
    { label: 'Currency', value: 'USD - United States Dollar' },
    { label: 'Annual Leave', value: '25 Days' },
    { label: 'Probation Period', value: '3 Months' },
  ];

  // ── Timeline ──────────────────────────────────────────────
  readonly timeline: TimelineStep[] = [
    {
      label: 'Offer Generated',
      date: 'May 12, 2024 - 09:30 AM',
      sub: 'Generated by Alex Rivera',
      completed: true,
    },
    {
      label: 'Internal Approval',
      date: 'May 12, 2024 - 11:45 AM',
      sub: 'Approved by Sarah Thompson (VP Engineering)',
      completed: true,
    },
    {
      label: 'Sent to Candidate',
      date: 'May 12, 2024 - 02:15 PM',
      sub: 'Delivered via DocuSign',
      completed: true,
    },
    {
      label: 'Candidate Decision',
      date: 'Pending response...',
      sub: '',
      completed: false,
    },
  ];

  // ── Documents ─────────────────────────────────────────────
  readonly documents: Document[] = [
    { icon: 'picture_as_pdf', iconColor: 'text-red-500', name: 'Offer_Letter_V2.pdf' },
    { icon: 'article', iconColor: 'text-blue-500', name: 'Employee_Handbook.pdf' },
  ];

  // ── Star helpers ──────────────────────────────────────────
  readonly fullStars = Array(4);

  // ── Actions ───────────────────────────────────────────────
  onAccept(): void {
    console.log('Offer accepted');
  }

  onReject(): void {
    console.log('Offer rejected');
  }

  onEdit(): void {
    console.log('Edit offer');
  }

  onDownload(doc: Document): void {
    console.log('Downloading:', doc.name);
  }

}
